site:
  title: DataStax Streaming Docs
  start_page: streaming::index.adoc
  url: https://docs.datastax.com/en/streaming
  # The keys.segmentIo site key must be in the site-publish playbook of each
  # docset. This loads Segment into the docset build, and is a requirement for
  # collecting site analytics.
  keys:
    segmentIo: 'd24gQtyKIUu5mLdkp11xjfiXLhRqx0HH'
    googleAnalytics: 'UA-20879577-1'

content:
  sources:
    # DATASTAX STREAMING DOCUMENTATION MAIN PAGE
    - url: https://github.com/datastaxdocs/datastax-streaming-docs-site.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: site-main
      branches: 
        - main #not versioned
      tags: 
        - streaming

    # LUNA STREAMING DOCUMENTATION SITE
    - url: https://github.com/datastax/pulsar-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags: 
        - streaming
        - luna-streaming

    # ASTRA STREAMING DOCUMENTATION SITE
    - url: https://github.com/datastax/astra-streaming-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - main #not versioned
      tags:
        - streaming
        - astra-streaming
    
    # PULSAR LEARNING SITE
    - url: https://github.com/datastax/streaming-learning-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches: 
        - main #not versioned
      tags: 
        - streaming
        - learning

    # STARLIGHT SITE
    - url: https://github.com/datastax/starlight-for-kafka-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - kafka

    - url: https://github.com/datastax/starlight-for-rabbitmq-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - rabbitmq

    - url: https://github.com/datastax/starlight-for-jms-docs.git
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - jms

runtime:
  log:
    level: info
    failure_level: warn

asciidoc:
  attributes:
    page-pagination: ''
    sectanchors: ''
    sectlinks: ''
    idprefix: ''
    idseparator: '-'

  extensions:
    - lib/tabs-block.js

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: supplemental-ui

output:
  dir: '~/work/datastax-streaming-docs-site/build/site'

urls:
  # https://docs.antora.org/antora/latest/playbook/urls-redirect-facility/
  # https://docs.antora.org/antora/latest/page/page-aliases/
  redirect_facility: httpd

  latest_version_segment_strategy: redirect:from # https://docs.antora.org/antora/latest/playbook/urls-latest-version-segment-strategy/
  latest_version_segment: 'latest'
