site:
  title: LOCAL DataStax Streaming Docs
  start_page: streaming::index.adoc
  url: https://docs.datastax.com/en/streaming

content:
  sources:
    # DATASTAX STREAMING DOCUMENTATION MAIN PAGE
    - url: ../datastax-streaming-docs-site
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: site-main
      branches: 
        - new-landing-page #not versioned
      tags: 
        - streaming

    # LUNA STREAMING DOCUMENTATION SITE
    - url: ../pulsar-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags: 
        - streaming
        - luna-streaming

    # ASTRA STREAMING DOCUMENTATION SITE
    - url: ../astra-streaming-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - DOC-3530-landing-page #not versioned
      tags:
        - streaming
        - astra-streaming
    
    # PULSAR LEARNING SITE
    - url: ../streaming-learning-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches: 
        - main #not versioned
      tags: 
        - streaming
        - learning

    # STARLIGHT SITE
    - url: ../starlight-for-kafka-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - kafka

    - url: ../starlight-for-rabbitmq-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - rabbitmq

    - url: ../starlight-for-jms-docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      branches:
        - release/*
      tags:
        - streaming
        - jms

runtime:
  log:
    level: info
    failure_level: warn

asciidoc:
  attributes:
    page-pagination: ''
    sectanchors: ''
    sectlinks: ''
    idprefix: ''
    idseparator: '-'

  extensions:
    - lib/tabs-block.js

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: supplemental-ui

output:
  dir: build/site

urls:
  # https://docs.antora.org/antora/latest/playbook/urls-redirect-facility/
  # https://docs.antora.org/antora/latest/page/page-aliases/
  redirect_facility: httpd

  latest_version_segment_strategy: redirect:from # https://docs.antora.org/antora/latest/playbook/urls-latest-version-segment-strategy/
  latest_version_segment: 'latest'