name: Pull request closed

on:
  pull_request:
    types: [closed]

jobs:
  RemoveSite:
    name: Remove site
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v121
        with:
          token: ${{ secrets.DOCSBOT_DISPATCH_TOKEN }}
          repo: riptano/docsbot
          ref: main
          workflow: docsbot.yml
          inputs: '{"repository": "${{ github.repository }}","cmd": "remove-site","deploy-server": "coppi","deploy-dir-to-remove": "streaming-site/${{ github.event.pull_request.head.ref }}"}'