name: Issue closed or deleted

on:
  issues:
    types:
      - closed
      - deleted

jobs:
  RemoveSite:
    name: Remove site
    runs-on: ubuntu-latest
    steps:
      - name: URL encode title
        id: url_encode_title
        run: |
          function url_encode() {
            echo "$@" \
            | sed \
                -e 's/\(.*\)/\L\1/g' \
                -e 's/%/%25/g' \
                -e 's/ /-/g' \
                -e 's/!/%21/g' \
                -e 's/"/%22/g' \
                -e "s/'/%27/g" \
                -e 's/#/%23/g' \
                -e 's/(/%28/g' \
                -e 's/)/%29/g' \
                -e 's/+/%2b/g' \
                -e 's/,/%2c/g' \
                -e 's/-/-/g' \
                -e 's/:/%3a/g' \
                -e 's/;/%3b/g' \
                -e 's/?/%3f/g' \
                -e 's/@/%40/g' \
                -e 's/\$/%24/g' \
                -e 's/\&/%26/g' \
                -e 's/\*/%2a/g' \
                -e 's/\./%2e/g' \
                -e 's/\//%2f/g' \
                -e 's/\[/%5b/g' \
                -e 's/\\/%5c/g' \
                -e 's/\]/%5d/g' \
                -e 's/\^/%5e/g' \
                -e 's/_/%5f/g' \
                -e 's/`/%60/g' \
                -e 's/{/%7b/g' \
                -e 's/|/%7c/g' \
                -e 's/}/%7d/g' \
                -e 's/~/%7e/g'
          }

          title_url_encoded=$(url_encode "${{ github.event.issue.title }}")
          echo "::set-output name=title_url::$title_url_encoded"

      - uses: benc-uk/workflow-dispatch@v121
        with:
            token: ${{ secrets.DOCSBOT_DISPATCH_TOKEN }}
            repo: riptano/docsbot
            ref: main
            workflow: remove-site_command.yml
            inputs: '{"deploy-server": "coppi","deploy-dir": "streaming-docs/${{ steps.url_encode_title.outputs.title_url }}"}'

