name: Docsbot Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  dispatchCommand:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3.0.1
        with:
          commands: deploy-site
          issue-type: pull-request
          token: ${{ secrets.DOCSBOT_DISPATCH_TOKEN }}
          repository: riptano/docsbot
          reactions: false
          permission: write
          allow-edits: false
          event-type-suffix: ''
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            cmd="deploy-site"
            doc-name=datastaxStreaming
            npm-script="build:prod"
            deploy-server=coppi
            doc-overrides="deployDir=streaming-site/${{ github.event.pull_request.head.ref }}"